### ISSUE TITLE
How feasible would WordPress-like named arguments and default values be?

### ISSUE THREAD

**Issue by qrazi** [fredericseiler/shortcoder#1]
Came across your plugin because I was looking for WordPress-like shortcode-plugins that do not actually use WordPress, GPL'ed code.

Now that I am trying to implement, I realize however that named argument with default values are missing. Is this a conscious decision? Do you have a general direction how to implement them? I could try and come up with a PR then?

**Comment by fredericseiler** [comment]
Can you give me an example in pseudo code?
